/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : DPI
 #	author : miyako
 #	2018/12/20
 #
 # --------------------------------------------------------------------------------*/



// --- DPI
void Get_system_DPI(sLONG_PTR *pResult, PackagePtr pParams);
